global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'xgoal-backend'
    scheme: https
    static_configs:
      - targets: ['xgoal-backend-production.up.railway.app']
    metrics_path: /metrics
